image: alpine/latest
packages:
  - go
  - bash
  - curl
  - icu
  - gcompat
tasks:
  - setup-dotnet: |
      curl -fsSL https://dot.net/v1/dotnet-install.sh > dotnet-install.sh
      bash dotnet-install.sh -c 6.0
      export PATH=~/.dotnet/:$PATH
      dotnet tool install --global dotnet-format
  - setup-protobuf: |
      go install \
      github.com/bufbuild/buf/cmd/buf@latest \
      github.com/bufbuild/buf/cmd/protoc-gen-buf-breaking@latest \
      github.com/bufbuild/buf/cmd/protoc-gen-buf-lint@latest
      go install github.com/harmony-development/hrpc/protoc-gen-hrpc@latest
  - build: |
      curl https://raw.githubusercontent.com/harmony-development/harmony-dotnet-sdk/main/build.sh | sh
  - push-nuget: |
      cd build
      dotnet pack
      dotnet nuget push bin/Debug/*.nupkg -k "$(cat ~/.nuget-token)" --source https://api.nuget.org/v3/index.json
  - push-git: |
      cd build
      git init
      git add -A
      git commit -m "chore: generate code"
      git branch -m gen
      git remote add origin ssh://git@github.com/harmony-development/harmony-dotnet-sdk.git
      git push --force
